# CircleCI 2.0 configuration file
#
---
version: 2.1
jobs:
  build_install_run:
    docker:
      # see https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.5
      - image: circleci/python:3.6
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: build, install, and run using provided shell script
          command: |
            pwd
            echo
            env | sort
            echo
            ls -las .
            echo
            uname -a
            echo
            python --version
            echo
            pip --version
            echo
            build-install.sh
workflows:
  version: 2
  workflow_1:
    jobs:
      - build_install_run
