# CircleCI 2.0 configuration file
# image list at https://circleci.com/docs/2.0/circleci-images/
---
version: 2.1
jobs:
  build_install_run_py35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: build, install, and run using provided shell script in Python 3.5
          command: |
            ./.circleci/build_install_run.sh
  build_install_run_py36:
    docker:
      
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: build, install, and run using provided shell script in Python 3.6
          command: |
            ./.circleci/build_install_run.sh
  build_install_run_py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: build, install, and run using provided shell script in Python 3.7
          command: |
            set -x
            whoami
            pwd
            env | sort
            ls -la .
            ./.circleci/build_install_run.sh
workflows:
  version: 2
  workflow_py:
    jobs:
      - build_install_run_py35
      - build_install_run_py36
      - build_install_run_py37
